[tool.poetry]
name = "app"
version = "0.0.1"
description = "Ultimate FastAPI"
authors = ["Luis Zavala"]

[tool.poetry.dependencies]
python = "^3.6"
uvicorn = "~0.11.3"
fastapi = "~0.68.0"
python-multipart = "~0.0.5"
pydantic = {extras = ["email"], version = "~1.8.1"}

[tool.poetry.dev-dependencies]
pytest = "^3.4"